[package]
name = "zkevm"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pairing = { git = 'https://github.com/appliedzkp/pairing', package = "pairing_bn256" }
halo2_proofs = { git = "https://github.com/scroll-tech/halo2.git", rev = "37d0c7e" }
bus-mapping = { git = "https://github.com/scroll-tech/zkevm-circuits", rev = "b7e31419" }
eth-types = { git = "https://github.com/scroll-tech/zkevm-circuits", rev = "b7e31419" }
zkevm-circuits = { git = "https://github.com/scroll-tech/zkevm-circuits", rev = "b7e31419", features = ["test"] }
rand = "0.8"
rand_xorshift = "0.3"
is-even = "1.0.0"
ethers-core = "0.6.0"
hex = "0.4.3"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0.66"
types = { path = "../types", features = ["test"] }
log = "0.4"
anyhow = "1.0"
blake2 = "0.10.3"
dotenv = "0.15.0"
env_logger = "0.9.0"
strum = "0.24"
strum_macros = "0.24"

[features]
default = ["prove_verify"]
prove_verify = []
